# Permalinks
permalink:              pretty
relative_permalinks:    true

# Setup
highlighter:        pygments
safe:               true
lsi:                false
encoding:           utf-8
title:              "@Jangid"
tagline:            My mind speaks
url:                http://jangid.github.io/
paginate:           1
baseurl:            ""
author:
  name:             Pankaj Jangid
  email:            pankaj.jangid@gmail.com
