# Permalinks
permalink:           pretty

# Setup
title:              Pankaj Jangid
tagline:            'I write code.'
description: > 
  I am an entrepreneur. I am writing code since 1996 and consider myself a geek. 
  I am a big fan of Indian Prime Minister Narendra Damodardas Modi.
url:                "https://jangid.github.io" # the base hostname & protocol for your site
baseurl:            "" # the subpath of your site, e.g. /blog/
paginate:            5
version: 1.0.0

# About/contact
author:
  name:              Pankaj Jangid
  url:               https://jangid.github.io
  email:             pankaj.jangid@gmail.com
  twitter:           http://twitter.com/jangid
  twitter_handle:    jangid
  facebook:          http://facebook.com/public.profile.of.pankaj
  facebook_username: public.profile.of.pankaj

# Custom vars
version:             1.0.0

# Github
github:
  repo: "http://github.com/jangid/jangid.github.io"

#Build settings
markdown:           kramdown
