# Site settings
title: Pankaj Jangid
email: pankaj.jangid@gmail.com
description: > 
  I am an entrepreneur. I consider myself a geek. I am coding since 1996 when I first got
  into graduate course. I am a big fan of Linus, RMS and
  Indian Prime Minister Narendra Modi.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jangid.github.io" # the base hostname & protocol for your site
twitter_username: jangid
github_username:  jangid
facebook_username: jangid

# Build settings
markdown: kramdown
